#!/bin/bash

ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc
echo "pt_BR.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=pt_BR.UTF-8" > /etc/locale.conf
echo "KEYMAP=$1" > /etc/vconsole.conf
echo $2 > /etc/hostname
echo "127.0.0.1 localhost.localdomain   localhost" >> /etc/hosts
echo "::1               localhost.localdomain   localhost" >> /etc/hosts
echo "127.0.1.1         $2.$3 $2" >> /etc/hosts
mkinitcpio -P
grub-install --target=x86_64-efi --bootloader-id=grub_uefi
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable espeakup
alsactl store
systemctl enable NetworkManager
echo "Agora digite o password duas vezes pro root quando pedido"
sleep 5
passwd

echo "Terminou o config"
