#!/bin/bash

grub-install --target=x86_64-efi --bootloader-id=grub_uefi
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable espeakup
alsactl store
systemctl enable NetworkManager

echo "Terminou o finish-script"
