#!/bin/bash

# Gerando swapfile
dd if=/dev/zero of=/mnt/swapfile bs=1M count=$1
chmod 600 /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/swapfile

# Instalando arch com espeakup
pacstrap /mnt base linux linux-firmware espeakup alsa-utils grub efibootmgr nano networkmanager links
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt

echo "Terminou swap-install"
